global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@monitoring.com'

route:
  receiver: 'default-receiver'
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 10s
  group_by: [cluster, alertname]
  routes:
  - receiver: 'slack'
    group_wait: 5s
    match_re:
      service: activemq

receivers:
  - name: 'default-receiver'
    email_configs:
    - to: '[ENTER DEFAULT EMAIL RECEIVER IF SMART SMTP IS ENABLED ON HOST]'

  - name: 'slack'
    slack_configs:
    - api_url: https://hooks.slack.com/services/[ENTER SLACK API KEY]
      channel: '#general'
      title: 'ActiveMQ Alerts'
      text: "<!channel>\nSummary: {{ .CommonAnnotations.summary }}\nImpact: {{ .CommonAnnotations.impact }}\nMore Info: {{ .CommonAnnotations.runbook }}"
